config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  # direct :donate do |form: 'adkinsforohio', ref: 'website', amount: nil, recurring: false|
  #   url = "https://secure.actblue.com/donate/#{form}?refcode=#{ref}"
  #   url += "&amount=#{amount}" unless amount.nil?
  #   url += '&recurring=1' if recurring
  #   url
  # end

  direct :facebook do
    'https://www.facebook.com/adkinsforohio'
  end

  direct :twitter do
    'https://www.twitter.com/adkinsforohio'
  end

  direct :instagram do
    'https://www.instagram.com/adkinsforohio'
  end

  direct :gitlab do
    'https://gitlab.com/mythcoders/adkinsforohio'
  end

  direct :youtube do
    'https://www.youtube.com/channel/UCc8anT7XR-VvBHfYX9XHS8g'
  end

  direct :reddit do
    'https://www.reddit.com/u/adkinsforohio'
  end

  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'endorsements', to: 'home#endorsements'
  get 'events', to: 'home#events'
  get 'volunteer', to: 'volunteer#index'
  post 'volunteer', to: 'volunteer#create', as: 'new_volunteer'

  scope :news do
    root to: 'news#index', as: 'news'
    get 'sb208-abortion-misinformation', to: 'news#sb208', as: 'news_sb208'
    get 'suspension', to: 'news#suspension', as: 'news_suspension'
  end

  scope :issues do
    root to: 'issues#index', as: 'issues'
    get 'healthcare', to: 'issues#healthcare'
    get 'education', to: 'issues#education'
    get 'economy', to: 'issues#economy'
    get 'democracy', to: 'issues#democracy'
    get 'environment', to: 'issues#environment'
    get 'technology', to: 'issues#technology'
    get 'guns', to: 'issues#guns'
    get 'justice', to: 'issues#justice'
    get 'lgbtq', to: 'issues#lgbtq'
    get 'womens_rights', to: 'issues#womens_rights'
    get 'rural', to: 'issues#rural'
    get 'seniors', to: 'issues#seniors'
    get 'transportation', to: 'issues#transportation'
    get 'veterans', to: 'issues#veterans'
  end

  get '/missioncontrol' => redirect('/mc')
  get '/mission_control' => redirect('/mc')
  scope module: :mission_control, path: 'mc', as: 'mc' do
    root to: 'dashboard#index', as: 'dashboard'
    get 'finances', to: 'dashboard#finances', as: 'finances_dashboard'
    get 'about', to: 'dashboard#about', as: 'about'
    resources :call_sessions
    resources :contacts
    resources :contribution_forms
    resources :contribution_types
    resources :contributions
    resources :events
    resources :expense_types
    resources :expenses
    resources :political_parties
    resources :volunteer_duties
  end
end

app/controllers/mission_control/call_sessions_controller.rb
# frozen_string_literal: true

module MissionControl
  class CallSessionsController < MissionControlController
    def index; end
  end
end

app/controllers/mission_control/contacts_controller.rb
# frozen_string_literal: true

module MissionControl
  class ContactsController < MissionControlController
    include ContactsHelper

    before_action :set_contact, only: %i[show edit update destroy]
    before_action :set_parties, only: %i[new edit]

    def index
      @contacts = Contact.all.sort_by(&:name)
    end

    def new
      @contact = Contact.new
    end

    def create
      @contact = Contact.new contact_params
      @contact.manually!
      if @contact.save
        flash[:success] = t('create.success')
        redirect_to mc_contact_path @contact
      else
        flash[:error] = t('create.failure')
        set_parties
        render 'new'
      end
    end

    def update
      if @contact.update(contact_params)
        flash[:success] = t('update.success')
        redirect_to mc_contact_path @contact
      else
        flash[:error] = t('update.failure')
        set_parties
        render 'edit'
      end
    end

    def destroy
      if @contact.delete
        flash[:success] = t('destroy.success')
        redirect_to mc_contacts_path
      else
        flash[:error] = t('destroy.failure')
        redirect_to mc_contact_path @contact
      end
    end

    private

    def contact_params
      params.require(:contact).permit(:id, :first_name, :middle_name, :last_name, :organization_name,
                                      :address, :city, :state, :zip_code, :phone_number, :email, :employer,
                                      :birth_year, :voter_id, :voter_status, :precinct, :house, :senate,
                                      :congressional, :village, :township, :school, :political_party_id,
                                      volunteer_duty_ids: [])
    end

    def set_contact
      @contact = Contact.find params[:id]
    end

    def set_parties
      @parties = PoliticalParty.active.order(:name)
    end
  end
end

app/controllers/mission_control/contribution_forms_controller.rb
# frozen_string_literal: true

module MissionControl
  class ContributionFormsController < MissionControlController
    def index
      @forms = ContributionForm.all
    end
  end
end

app/controllers/mission_control/contribution_types_controller.rb
# frozen_string_literal: true

module MissionControl
  class ContributionTypesController < MissionControlController
    def index
      @types = ContributionType.all
    end
  end
end

app/controllers/mission_control/contributions_controller.rb
# frozen_string_literal: true

module MissionControl
  class ContributionsController < MissionControlController
    before_action :set_contribution, only: %i[show edit update destroy]
    before_action :set_dropdown_values, only: %i[new edit]

    def index
      @contributions = Contribution.all
    end

    def new
      @contribution = Contribution.new(contact_id: params[:contact_id])
    end

    def create
      @contribution = Contribution.new contribution_params
      if @contribution.save
        flash[:success] = t('create.success')
        redirect_to edit_mc_contribution_path @contribution
      else
        flash[:error] = t('create.failure')
        set_dropdown_values
        render 'new'
      end
    end

    def update
      if @contribution.update(contribution_params)
        flash[:success] = t('update.success')
        redirect_to edit_mc_contribution_path @contribution
      else
        flash[:error] = t('update.failure')
        set_dropdown_values
        render 'edit'
      end
    end

    def destroy
      @contribution.delete_at = Time.current
      if @contribution.save
        flash[:success] = t('destroy.success')
        redirect_to mc_contributions_path
      else
        flash[:error] = t('destroy.failure')
        redirect_to mc_contribution_path @contribution
      end
    end

    private

    def contribution_params
      parameters = params.require(:contribution)
                          .permit(:id, :contact_id, :contribution_date, :amount, :description, :thanked,
                                  :contribution_type_id, :contribution_form_id, :event_id, :deleted_at)
      parameters[:contribution_date] = convert_date(parameters[:contribution_date])
      parameters[:deleted_at] = convert_datetime(parameters[:deleted_at])
      parameters
    end

    def set_contribution
      @contribution = Contribution.find params[:id]
    end

    def set_dropdown_values
      @contacts = Contact.all.sort_by(&:name)
      @types = ContributionType.active
      @forms = ContributionForm.active
      @events = Event.fundraisers
    end
  end
end

app/controllers/mission_control/dashboard_controller.rb
# frozen_string_literal: true

module MissionControl
  class DashboardController < MissionControlController
    def index
      @recent_contacts = Contact.recent.organic.count
    end
  end
end

app/controllers/mission_control/events_controller.rb
# frozen_string_literal: true

module MissionControl
  class EventsController < MissionControlController
    before_action :set_event, only: %i[show edit update destroy]

    def index
      @events = Event.all
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new event_params
      if @event.save
        flash[:success] = t('create.success')
        redirect_to mc_event_path @event
      else
        flash[:error] = t('create.failure')
        render 'new'
      end
    end

    def update
      if @event.update(event_params)
        flash[:success] = t('update.success')
        redirect_to mc_event_path @event
      else
        flash[:error] = t('update.failure')
        render 'edit'
      end
    end

    def destroy
      if @event.delete
        flash[:success] = t('destroy.success')
        redirect_to mc_events_path
      else
        flash[:error] = t('destroy.failure')
        redirect_to mc_event_path @event
      end
    end

    private

    def event_params
      parameters = params.require(:event).permit(:id, :name, :start, :end, :description, :rsvp_link, :fundraiser)
      parameters[:start] = convert_datetime(parameters[:start])
      parameters[:end] = convert_datetime(parameters[:end])
      parameters
    end

    def set_event
      @event = Event.find params[:id]
    end
  end
end

app/controllers/mission_control/expense_types_controller.rb
# frozen_string_literal: true

module MissionControl
  class ExpenseTypesController < MissionControlController
    def index
      @types = ExpenseType.all
    end
  end
end

app/controllers/mission_control/expenses_controller.rb
# frozen_string_literal: true

module MissionControl
  class ExpensesController < MissionControlController
    before_action :set_expense, only: %i[show edit update destroy]
    before_action :set_dropdown_values, only: %i[new edit]

    def index
      @expenses = Expense.all
    end

    def new
      @expense = Expense.new(contact_id: params[:contact_id])
    end

    def create
      @expense = Expense.new expense_params
      if @expense.save
        flash[:success] = t('create.success')
        redirect_to edit_mc_expense_path @expense
      else
        flash[:error] = t('create.failure')
        set_dropdown_values
        render 'new'
      end
    end

    def update
      if @expense.update(expense_params)
        flash[:success] = t('update.success')
        redirect_to edit_mc_expense_path @expense
      else
        flash[:error] = t('update.failure')
        set_dropdown_values
        render 'edit'
      end
    end

    def destroy
      @contribution.delete_at = Time.current
      if @expense.save
        flash[:success] = t('destroy.success')
        redirect_to mc_expenses_path
      else
        flash[:error] = t('destroy.failure')
        redirect_to mc_expense_path @expense
      end
    end

    private

    def expense_params
      parameters = params.require(:expense)
                          .permit(:id, :contact_id, :expense_date, :amount, :description,
                                  :expense_type_id, :event_id, :deleted_at)
      parameters[:expense_date] = convert_date(parameters[:expense_date])
      parameters[:deleted_at] = convert_datetime(parameters[:deleted_at])
      parameters
    end

    def set_expense
      @expense = Expense.find params[:id]
    end

    def set_dropdown_values
      @contacts = Contact.all.sort_by(&:name)
      @types = ExpenseType.active
      @events = Event.fundraisers
    end
  end
end

app/controllers/mission_control/mission_control_controller.rb
# frozen_string_literal: true

module MissionControl
  class MissionControlController < ApplicationController
    before_action :authenticate_user!
    layout 'mission_control'
  end
end

app/controllers/mission_control/political_parties_controller.rb
# frozen_string_literal: true

module MissionControl
  class PoliticalPartiesController < MissionControlController
    def index
      @parties = PoliticalParty.all
    end
  end
end

app/controllers/mission_control/volunteer_duties_controller.rb
# frozen_string_literal: true

module MissionControl
  class VolunteerDutiesController < MissionControlController
    def index
      @duties = VolunteerDuty.all
    end
  end
end

app/views/mission_control/expenses/_form.html.haml
.card
  .card-header
    %h3.card-header-title
      Information
  .card-body
    = f.hidden_field :id
    .form-row
      .form-group.col-12.col-lg-9
        = f.label :description, class: 'col-form-label'
        = f.text_field :description, class: 'form-control'
      .form-group.col-12.col-lg-3
        = f.label :expense_date, class: 'col-form-label'
        #expensepicker.input-group.date{"data-target-input": "nearest", 'data-date-picker': ''}
          = f.text_field :expense_date, value: l_present(@expense.expense_date), class: 'form-control datepicker-input', 'data-target': '#expensepicker'
          .input-group-append{"data-target": "#expensepicker", "data-toggle": "datetimepicker"}
            .input-group-text
              %i.fad.fa-calendar
    .form-row
      .form-group.col-12.col-lg-3
        = f.label :amount, class: 'col-form-label'
        .input-group
          .input-group-prepend
            %span.input-group-text
              %i.fad.fa-dollar-sign
          = f.text_field :amount, class: 'form-control'
      .form-group.col-12.col-lg-3
        = f.label :expense_type_id, class: 'col-form-label'
        = f.select :expense_type_id,
          options_from_collection_for_select(@types, 'id', 'name', @expense.expense_type_id),
          { include_blank: '- Select -' },
          { class: 'form-control', 'data-toggle': 'select' }
      .form-group.col-12.col-lg-6
        = f.label :contact_id, class: 'col-form-label'
        = f.select :contact_id,
          options_from_collection_for_select(@contacts, 'id', 'name', @expense.contact_id),
          { include_blank: '- Select -' },
          { class: 'form-control', 'data-toggle': 'select' }
      .form-group.col-12.col-lg-6
        = f.label :event_id, class: 'col-form-label'
        = f.select :event_id,
          options_from_collection_for_select(@events, 'id', 'name', @expense.event_id),
          { include_blank: '- Select -' },
          { class: 'form-control', 'data-toggle': 'select' }
      .form-group.col-12.col-lg-3
        = f.label :deleted_at, class: 'col-form-label'
        #deletedpicker.input-group.date{"data-target-input": "nearest", 'data-date-time-picker': ''}
          = f.text_field :deleted_at, value: l_present(@expense.deleted_at), class: 'form-control datepicker-input', 'data-target': '#deletedpicker'
          .input-group-append{"data-target": "#deletedpicker", "data-toggle": "datetimepicker"}
            .input-group-text
              %i.fad.fa-calendar

app/views/mission_control/expenses/edit.html.haml
= form_for @expense, url: mc_expense_path(@expense), method: :patch do |f|
  .header.mt-md-5
    .header-body
      .row.align-items-center
        .col
          %h6.header-pretitle
            Finances
          %h1.header-title
            %i.fad.fa-file-invoice
            Edit Expense
        .col-auto
          = link_to 'Cancel', mc_expenses_path, class: 'btn btn-link text-muted'
          = f.submit 'Save Changes', class: 'btn btn-success lift'
  = render partial: 'form', locals: { f: f }

app/views/mission_control/expenses/index.html.haml
.header.mt-md-5
  .header-body
    .row.align-items-center
      .col
        %h6.header-pretitle
          Overview
        %h1.header-title
          %i.fad.fa-file-invoice
          Expenses
      .col-auto
        = link_to 'New Expense', new_mc_expense_path, class: 'btn btn-primary lift'
.card
  .table-responsive
    %table.table.table-sm.card-table
      %thead
        %tr
          %th
          %th Date
          %th Vendor
          %th Descirption
          %th Type
          %th Amount
      %tbody
        - @expenses.each do |c|
          %tr
            %td.action-column
              = link_to 'Edit', edit_mc_expense_path(c), class: 'btn btn-outline-secondary btn-sm'
              - if c.deleted_at.present?
                .badge.badge-soft-danger.mt-2 Deleted
            %td= l_present c.expense_date
            %td= c.contact.name
            %td= c.description
            %td= c.type.name
            %td= number_to_currency c.amount

app/views/mission_control/expenses/new.html.haml
= form_for @expense, url: mc_expenses_path do |f|
  .header.mt-md-5
    .header-body
      .row.align-items-center
        .col
          %h6.header-pretitle
            Finances
          %h1.header-title
            %i.fad.fa-file-invoice
            New Expense
        .col-auto
          = link_to 'Cancel', mc_expenses_path, class: 'btn btn-link text-muted'
          = f.submit 'Create', class: 'btn btn-success lift'
  = render partial: 'form', locals: { f: f }

app/views/mission_control/expenses/show.html.haml
.header.mt-md-5
  .header-body
    .row.align-items-center
      .col
        %h6.header-pretitle
          Work In Progress
        %h1.header-title
          %i.fad.fa-exclamation-triangle
          Coming Soon