config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  # direct :donate do |form: 'adkinsforohio', ref: 'website', amount: nil, recurring: false|
  #   url = "https://secure.actblue.com/donate/#{form}?refcode=#{ref}"
  #   url += "&amount=#{amount}" unless amount.nil?
  #   url += '&recurring=1' if recurring
  #   url
  # end

  direct :facebook do
    'https://www.facebook.com/adkinsforohio'
  end

  direct :twitter do
    'https://www.twitter.com/adkinsforohio'
  end

  direct :instagram do
    'https://www.instagram.com/adkinsforohio'
  end

  direct :gitlab do
    'https://gitlab.com/mythcoders/adkinsforohio'
  end

  direct :youtube do
    'https://www.youtube.com/channel/UCc8anT7XR-VvBHfYX9XHS8g'
  end

  direct :reddit do
    'https://www.reddit.com/u/adkinsforohio'
  end

  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'endorsements', to: 'home#endorsements'
  get 'events', to: 'home#events'
  get 'volunteer', to: 'volunteer#index'
  post 'volunteer', to: 'volunteer#create', as: 'new_volunteer'

  scope :news do
    root to: 'news#index', as: 'news'
    get 'sb208-abortion-misinformation', to: 'news#sb208', as: 'news_sb208'
    get 'suspension', to: 'news#suspension', as: 'news_suspension'
  end

  scope :issues do
    root to: 'issues#index', as: 'issues'
    get 'healthcare', to: 'issues#healthcare'
    get 'education', to: 'issues#education'
    get 'economy', to: 'issues#economy'
    get 'democracy', to: 'issues#democracy'
    get 'environment', to: 'issues#environment'
    get 'technology', to: 'issues#technology'
    get 'guns', to: 'issues#guns'
    get 'justice', to: 'issues#justice'
    get 'lgbtq', to: 'issues#lgbtq'
    get 'womens_rights', to: 'issues#womens_rights'
    get 'rural', to: 'issues#rural'
    get 'seniors', to: 'issues#seniors'
    get 'transportation', to: 'issues#transportation'
    get 'veterans', to: 'issues#veterans'
  end

  get '/missioncontrol' => redirect('/mc')
  get '/mission_control' => redirect('/mc')
  scope module: :mission_control, path: 'mc', as: 'mc' do
    root to: 'dashboard#index', as: 'dashboard'
    get 'finances', to: 'dashboard#finances', as: 'finances_dashboard'
    get 'about', to: 'dashboard#about', as: 'about'
    resources :call_sessions
    resources :contacts
    resources :contribution_forms
    resources :contribution_types
    resources :contributions
    resources :events
    resources :expense_types
    resources :expenses
    resources :political_parties
    resources :volunteer_duties
  end
end

app/controllers/issues_controller.rb
# frozen_string_literal: true

class IssuesController < ApplicationController
  layout 'landing', except: %i[index]
end

app/views/issues/tiles/_democracy.html.haml
.card.shadow-light-lg.mb-6.mb-md-0.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/democracy.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 4 proposals
      %h3.text-uppercase.text-danger
        Electoral reform
      %p.text-muted
        Expensive campaigns have moved control out of the hands of the individual voters.
        Extensive Gerrymandering has forced politicians to pursue divisive policies while
        avoiding elective primaries.
      = link_to democracy_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_economy.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url('issues/economy.jpg')}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 4 proposals
      %h3.text-uppercase.text-danger
        Economic opportunities
      %p.text-muted
        Corporations do everything to minimize tax liability and benefits to employees while maximizing profits
        for CEOs and shareholders. Our hard work should benefit us, not just corporations.
      = link_to economy_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_education.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url('issues/education.jpg')}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 6 proposals
      %h3.text-uppercase.text-danger
        Pre K-12 & Higher Education
      %p.text-muted
        The quality of a child's education shouldn't depend on their zip code.
        I lived through our unconstitutional school funding, attending public, charter, and online schools;
        Graduating from the home of DeRolph V. State.
      = link_to education_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_environment.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/environment.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 4 proposals
      %h3.text-uppercase.text-danger
        The Environment & Clean Energy
      %p.text-muted
        Corporations knew about the impact of fossil fuels in the 1970s. The government knew in the 1980s.
        In the past forty years, the free market hasn't solved the problem. We must do everything we can to
        ensure the survival of our children and resources.
      = link_to environment_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_guns.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/gunsafety.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 5 proposals
      %h3.text-uppercase.text-danger
        Gun rights & safety
      %p.text-muted
        It's not difficult to have common sense solutions that balance public safety with the rights of gun
        owners. At the same time, we can increase the enforcement of existing laws to assist with keeping our
        communities safe.
        -# = link_to guns_path, class: 'btn btn-primary-soft btn-block' do
        -#   Learn more
        -#   %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_healthcare.html.haml
.card.shadow-light-lg.mb-6.mb-md-0.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url('issues/healthcare.jpg')}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 4 proposals
      %h3.text-uppercase.text-danger
        Healthcare & Perscription Drugs
      %p.text-muted
        Affordable healthcare and prescription drugs are a right, not a privilege.
        Ohioans must pay hundreds of dollars a month for life-saving drugs like Insulin and EpiPen's even
        with health insurance coverage.
      = link_to healthcare_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_justice.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/justice.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-warning
          %span.h6.text-uppercase Proposals being finalized
      %h3.text-uppercase.text-danger
        Criminal Justice reform
      %p.text-muted
        The prison industrial complex has pushed policies that ensure continued profits for private prisons.
        It's immoral. Our solutions have to focus on rehabilitation rather than punishment.

app/views/issues/tiles/_lgbtq.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/lgbtq.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 3 proposals
      %h3.text-uppercase.text-danger
        LGBTQ+
      %p.text-muted
        Everyone has the right to love who they want and to express ourselves without the interference of others.
      = link_to lgbtq_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_rural.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/rural.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-warning
          %span.h6.text-uppercase Proposals being finalized
      %h3.text-uppercase.text-danger
        Rural Ohio
      %p.text-muted
        Our rural communities haven't fully recovered from the recession and are continuing
        to face challenges. We need new policies that guarantee these communities aren't
        left behind and that the small-town way of life survives.

app/views/issues/tiles/_seniors.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/seniors.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-warning
          %span.h6.text-uppercase Proposals being finalized
      %h3.text-uppercase.text-danger
        Seniors
      %p.text-muted
        Retirement shouldn't be a part-time job and worrying about how to pay for
        prescriptions and medical expenses.
      /
        <a href="<haml_loud> issues_path </haml_loud>" class="btn btn-primary-soft btn-block">
        Learn more <i class="fas fa-arrow-right ml-3"></i>
        </a>

app/views/issues/tiles/_technology.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/technology.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 4 proposals
      %h3.text-uppercase.text-danger
        Privacy & Technology
      %p.text-muted
        Businesses have profited off data collected about us as we use apps and browse the web. Companies
        must compete fairly and in the interest of consumers.
      = link_to technology_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3

app/views/issues/tiles/_transportation.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/transportation.png")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-warning
          %span.h6.text-uppercase Proposals being finalized
      %h3.text-uppercase.text-danger
        Transportation
      %p.text-muted
        Gas Tax increases aren't able to solve all our transportation problems.
        We need to prepare for the future and invest in alternative modes of transportation.

app/views/issues/tiles/_veterans.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/veterans.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-warning
          %span.h6.text-uppercase Proposals being finalized
      %h3.text-uppercase.text-danger
        Veterans
      %p.text-muted
        They've served our country, but we've not held up our obligations to them.
        Ohio must fill the void created by the shortcomings of the Federal government.

app/views/issues/tiles/_womens_rights.html.haml
.card.shadow-light-lg.lift.lift-lg
  %img.card-img-top{alt: "...", src: asset_url("issues/women.jpg")}
    .position-relative
      .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
        %svg{fill: "none", preserveAspectRatio: "none", viewBox: "0 0 1440 24"}
          %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
    .card-body.position-relative
      .position-relative.text-right.mt-n8.mr-n4.mb-3
        %span.badge.badge-pill.badge-primary
          %span.h6.text-uppercase 3 proposals
      %h3.text-uppercase.text-danger
        Women's rights & equality
      %p.text-muted
        It's a fundamental right for a woman to have control of her body. That right needs to be defended and
        expanded. We also have to eliminate the pay discrimination that women face.
      = link_to womens_rights_path, class: 'btn btn-primary-soft btn-block' do
        Learn more
        %i.fad.fa-chevron-double-right.ml-3