config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  # direct :donate do |form: 'adkinsforohio', ref: 'website', amount: nil, recurring: false|
  #   url = "https://secure.actblue.com/donate/#{form}?refcode=#{ref}"
  #   url += "&amount=#{amount}" unless amount.nil?
  #   url += '&recurring=1' if recurring
  #   url
  # end

  direct :facebook do
    'https://www.facebook.com/adkinsforohio'
  end

  direct :twitter do
    'https://www.twitter.com/adkinsforohio'
  end

  direct :instagram do
    'https://www.instagram.com/adkinsforohio'
  end

  direct :gitlab do
    'https://gitlab.com/mythcoders/adkinsforohio'
  end

  direct :youtube do
    'https://www.youtube.com/channel/UCc8anT7XR-VvBHfYX9XHS8g'
  end

  direct :reddit do
    'https://www.reddit.com/u/adkinsforohio'
  end

  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'endorsements', to: 'home#endorsements'
  get 'events', to: 'home#events'
  get 'volunteer', to: 'volunteer#index'
  post 'volunteer', to: 'volunteer#create', as: 'new_volunteer'

  scope :news do
    root to: 'news#index', as: 'news'
    get 'sb208-abortion-misinformation', to: 'news#sb208', as: 'news_sb208'
    get 'suspension', to: 'news#suspension', as: 'news_suspension'
  end

  scope :issues do
    root to: 'issues#index', as: 'issues'
    get 'healthcare', to: 'issues#healthcare'
    get 'education', to: 'issues#education'
    get 'economy', to: 'issues#economy'
    get 'democracy', to: 'issues#democracy'
    get 'environment', to: 'issues#environment'
    get 'technology', to: 'issues#technology'
    get 'guns', to: 'issues#guns'
    get 'justice', to: 'issues#justice'
    get 'lgbtq', to: 'issues#lgbtq'
    get 'womens_rights', to: 'issues#womens_rights'
    get 'rural', to: 'issues#rural'
    get 'seniors', to: 'issues#seniors'
    get 'transportation', to: 'issues#transportation'
    get 'veterans', to: 'issues#veterans'
  end

  get '/missioncontrol' => redirect('/mc')
  get '/mission_control' => redirect('/mc')
  scope module: :mission_control, path: 'mc', as: 'mc' do
    root to: 'dashboard#index', as: 'dashboard'
    get 'finances', to: 'dashboard#finances', as: 'finances_dashboard'
    get 'about', to: 'dashboard#about', as: 'about'
    resources :call_sessions
    resources :contacts
    resources :contribution_forms
    resources :contribution_types
    resources :contributions
    resources :events
    resources :expense_types
    resources :expenses
    resources :political_parties
    resources :volunteer_duties
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  layout 'landing', only: %i[index contact]

  def index
    @contact = Contact.new
  end
end

app/views/home/about.html.haml
- page_title 'Meet Justin'
.row.mt-5
  .col-12
    .row.mb-6
      .col-auto
        .icon-circle.bg-danger.text-white
          %i.fa.fa-user.fa-2x
      .col.ml-n4
        %h2.font-weight-bold.mb-0
          Meet Justin Adkins
        %p.font-size-lg.text-gray-700.mb-0
          Who he is and why he's running
  .col-12
    %p.mb-4
      %strong In a lot of ways, my story reflects the struggles of our state.
      I was born right here in Central OH while my
      parents were still enrolled at Whetstone High School. Like too many Ohioans, drug abuse and the opioid epidemic
      hit my family hard. My single mother struggled with addiction for much of my childhood.
    %p.mb-4
      By the time my family stepped in, I'd already been missing school to take care of my younger siblings, Brendan and
      Hayleigh. We soon moved in with our respective grandparents, and I was able to repeat the first grade in Columbus
      City Schools.
    %p.mb-4
      My grandparents, who raised me, divorced before the start of my freshman year, and it hit me pretty hard. I stayed
      and took care of my blind grandpa, but after a while, it was too hard balancing school and life at home. I dropped
      out of the charter school I was attending and finished the remainder of my freshman year at the now-defunct ECOT.
    %p.mb-4
      At the end of that year, I moved to Perry County with my aunt and uncle.
      %strong I graduated from Sheridan High School, which is literally in the middle of a cornfield.
      Sheridan is also home to the landmark DeRolph court case that ruled Ohio's school funding unconstitutional.
    %p.mb-4
      While most would probably see this as a difficult childhood, I like to think of it as life granting me a unique
      opportunity to experience all aspects of Ohio's unfair education system.
    %p.mb-4
      After graduating, I moved back up to Columbus and briefly attended DeVry University while working two jobs.
      Eventually, I got an internship and later full-time job with the Ohio Department of Public Safety.
      Soon after, I decided to drop out of DeVry so that I wouldn’t increase my loan debt any further.
    .card
      .row.no-gutters.shadow-light-lg
        .col-12.col-md-5
          %img.img-fluid.rounded-top.d-md-none{src: asset_path('JustinAlt.jpg'), style: "image-orientation: from-image;"}/
          .position-absolute.w-100.h-100.bg-cover.rounded-left.d-none.d-md-block{style: "background-image: url('#{asset_path('JustinAlt.jpg')}');"}
            .shape.shape-right.shape-fluid-y.svg-shim.text-white
              %svg{fill: "none", viewbox: "0 0 58 345", xmlns: "http://www.w3.org/2000/svg"}
                %path{d: "M58 0H51C76 212 0 345 0 345H58V0Z", fill: "currentColor"}
        .col-12.col-md-7
          %blockquote.blockquote.pt-7.pb-7.pt-md-10.pb-md-9.px-6.px-md-8.mb-0.bg-white.rounded-right.text-center
            %p.mb-5.mb-md-7
              My story is pretty unique for a political candidate.
              But it’s not unique for everyday Ohioans. And that’s why I’m running.
              In 2020, we have an opportunity to take back our state and set it on the right path.
              We need more leaders at the Statehouse who’ve been where I’ve been.
              Then we can propose solutions that we know from experience will work.
            %footer.blockquote-footer
              %span.h6.text-uppercase Justin Adkins, Democrat for Ohio Senate District 16
    %p.mb-4.mt-4
      %strong This first-hand experience proves that a college degree isn't the only path to a successful career.
      We can't lose sight of our skill and trade jobs.
    %p.mb-4
      But there were also so many times when my life could have easily taken a bad turn. Ohio kids shouldn’t have to
      spend their childhood fighting to avoid falling through the cracks.
    %p.mb-4
      I worked with Public Safety for nearly five years. My team and I helped further the department’s mission of
      creating a Safer Ohio while also saving taxpayers
      %strong over a $1 million/yr.
    %p.mb-4
      Then in 2016, my sister Hayleigh was having trouble at home. So, I stepped up, attained guardianship, and let her
      move in with me. I wasn't ready to raise a child, but I wanted to ensure that she graduated from Whetstone High
      School on time.
    %p.mb-4
      A year later, I started a technology company called MythCoders with my best friend. We offer technical services to
      other small businesses at affordable prices. Thankfully, we’re still chugging along and now have clients in
      Franklin and Perry Counties.
    %p.mb-4
      I currently work for CoverMyMeds and live just south of Worthington in Sharon Township with my two cats, Caesar
      and Cleopatra. When I'm not building websites, I'm a member of the Sharon Township Tech Committee, the Worthington
      Noon Lions Club, and the Franklin County Young Dems.
    %p.mb-4
      %strong As I've gotten older, I’ve realized that my story is too often just life in America.
    %p.mb-4
      I've watched friends and family barely able to afford life-saving Insulin despite having insurance.
      I've helped people file for divorce so they could qualify for Medicaid.
      And we've all read the horror stories of people turning to GoFundMe to help pay for large medical bills.
      In a nation as prosperous as ours, this is immoral. And we can do better. That’s why I support capping the costs
      of life-saving drugs and introducing a public insurance option to compete with insurance companies.
    %p.mb-4
      I know from experience that it's not possible to live off a wage of $8.55 an hour and have a middle-class life.
      That's why I've proposed a Living Wage Formula that restores the Dignity of Work by finally paying people what
      they're worth. My formula ensures all your monthly income doesn't go towards necessities like food, rent,
      utilities, and mandated auto insurance.
    %p.mb-4
      %strong In 2020, we have an opportunity to take back our state and set it on the right path.
      We need bold new leadership to tackle the challenges that lie ahead. We don’t have time for politics as usual.
    %p.mb-4
      My story is pretty unique for a political candidate.
      But it’s not unique for everyday Ohioans. And that’s why I’m running.
    %p.mb-4
      We need more leaders at the Statehouse who’ve been where I’ve been.
      Then we can propose solutions that we know from experience will work.
%section.pt-6
  .row.align-items-center
    .col-12.col-md
      %h3.font-weight-bold.mb-1.text-danger
        Join our team
      %p.font-size-lg.text-muted.mb-6.mb-md-0
        With your help, we can take back our government and get it working again for the people.
    .col-12.col-md
      %a.btn.btn-primary-soft.mr-1.lift{href: volunteer_path}
        Sign-up to volunteer
      -# %a.btn.btn-danger.lift{href: donate_url(ref: 'website-about')}
      -#   Make a contirbution
      -#   %i.fad.fa-chevron-double-right.d-none.d-md-inline.ml-3

app/views/home/contact.html.haml
- page_title 'Contact Us'
%section.py-10.py-md-15.overlay.overlay-black.overlay-60.bg-cover{style: "background-image: url('#{asset_path('DowntownWorthington.jpg')}');"}
  .container
    .row.justify-content-center
      .col-12.col-md-10.col-lg-8.text-center
        %h1.display-2.font-weight-bold.text-white
          We’re Here to Help.
        %p.lead.text-white-75.mb-0
          We always want to hear from you! Let us know how we can best help you and we'll do our very best.
.position-relative
  .shape.shape-bottom.shape-fluid-x.svg-shim.text-light
    %svg{fill: "none", preserveaspectratio: "none", viewbox: "0 0 1440 24", xmlns: "http://www.w3.org/2000/svg"}
      %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
%section#info.py-7.py-md-9.border-bottom.border-gray-300
  .container
    .row
      .col-12.text-center
        %a.btn.btn-white.btn-rounded-circle.shadow.mt-n11.mt-md-n13{"data-smooth-scroll": "", href: "#info"}
          %i.fa.fa-arrow-down
    .row.text-center
      -# .col-12.col-md-2.text-center.border-right.border-gray-300
      -#   %h6.text-uppercase.text-gray-700.mb-1
      -#     Message us
      -#   .mb-5.mb-md-0
      -#     %a.h4.text-primary{href: "http://m.me/adkinsforohio?ref=website-contact", target: "_blank"}
      -#       Start a chat!
      -# .col-12.col-md-2.text-center.border-right.border-gray-300
      -#   %h6.text-uppercase.text-gray-700.mb-1
      -#     Call anytime
      -#   .mb-5.mb-md-0
      -#     %a.h4{href: "#"}
      -#       (614) 598-6678
      .col-12
        %h6.text-uppercase.text-gray-700.mb-1.text-center
          Email us
        .mb-5.mb-md-0
          %a.h4{href: contact_link}= contact_email
      -# .col-12.col-md-4.text-center
      -#   %h6.text-uppercase.text-gray-700.mb-1
      -#     Mail us
      -#   .mb-5.mb-md-0
      -#     %a.h4{href: "#"}
      -#       163 W Kanawha Ave
      -#       %br/
      -#       Columbus, OH 43214

app/views/home/endorsements.html.haml
- page_title 'Endorsements'
.jumbotron
  %h1.display-4 Endorsements
  %p.lead Check back soon!

app/views/home/events.html.haml
- page_title 'Events'
#fb-root
%script{async: "", crossorigin: "anonymous", defer: "defer", src: "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3"}
.row.mt-5
  .col-12
    .row.mb-6.mb-md-8
      .col-auto
        .icon-circle.bg-danger.text-white
          %i.fa.fa-calendar-alt.fa-2x
      .col.ml-n4
        %h2.font-weight-bold.mb-0
          Upcoming Events
        %p.font-size-lg.text-gray-700.mb-0
          Come out and meet Justin
  .col-12.col-md-8
    .row
      -# .col-12.col-xl-6.d-flex.mb-2
      -#   %a.card.text-reset.text-decoration-none.shadow-light-lg.lift{href: "https://www.facebook.com/events/753195261841198/"}
      -#     .card-body.d-flex.flex-column
      -#       %h3 Coffee with the Candidate
      -#       %p.text-muted.mb-5
      -#         Highline Coffee
      -#         %br
      -#         Worthington, OH
      -#       .row.mt-auto.pt-5.border-top
      -#         .col
      -#           %h6.text-uppercase.text-muted.mb-0.text-primary
      -#             %time{datetime: "2020-01-11"}
      -#               Sat January 11, 2020
      -#               %br
      -#               10:00am-11:30am
      -# .col-12.col-xl-6.d-flex.mb-2
      -#   %a.card.text-reset.text-decoration-none.shadow-light-lg.lift{href: "https://www.facebook.com/events/2397309920374422/"}
      -#     .card-body.d-flex.flex-column
      -#       %h3 Coffee with the Candidate
      -#       %p.text-muted.mb-5
      -#         Transcend Coffee & Roastery
      -#         %br
      -#         Grove City, OH
      -#       .row.mt-auto.pt-5.border-top
      -#         .col
      -#           %h6.text-uppercase.text-muted.mb-0.text-primary
      -#             %time{datetime: "2020-03-17"}
      -#               Sat January 25, 2020
      -#               %br
      -#               10:00am-11:30am
      .col-12.col-xl-6.d-flex.mb-2
        %a.card.text-reset.text-decoration-none.shadow-light-lg.lift{href: "https://www.lettforohio.com/home"}
          .card-body.d-flex.flex-column
            %h3 Election Day
            %p.text-muted.mb-5
              Come out and vote for Crystal Lett at your local precinct!
            .row.mt-auto.pt-5.border-top
              .col
                %h6.text-uppercase.text-muted.mb-0.text-primary
                  %time{datetime: "2020-03-17"}
                    Tue March 17, 2020
                    %br
                    6:30am-7:30pm
  .col-12.col-md-4
    .fb-page{"data-adapt-container-width": "true", "data-height": "", "data-hide-cover": "false", "data-href": "https://www.facebook.com/AdkinsForOhio/", "data-show-facepile": "true", "data-small-header": "false", "data-tabs": "events,timeline", "data-width": ""}
      %blockquote.fb-xfbml-parse-ignore{cite: "https://www.facebook.com/AdkinsForOhio/"}
        %a{href: "https://www.facebook.com/AdkinsForOhio/"} Justin Adkins for Ohio Senate

app/views/home/index.html.haml
- page_title 'Home'

%section.pt-11.mt-5.bg-light.pb-5
  .container
    = render partial: 'layouts/partials/suspension'
    .row.align-items-center
      .col-12.col-md-5.col-lg-6.order-md-2
        %img.img-fluid.rounded.aos-init.aos-animate{alt: "...", "data-aos": "fade-up", "data-aos-delay": "100", src: asset_path('JustinMain.jpg')}
      .col-12.col-md-7.col-lg-6.order-md-1.aos-init.aos-animate{"data-aos": "fade-up"}
        %h1.display-3.text-center.text-md-left
          %span.text-danger Justin Adkins
          %br
          for
          %span.text-primary Ohio Senate 16
        %p.lead.text-center.text-md-left.text-muted.mb-6
          %a{href: about_path} My story
          is pretty unique for a political candidate.
          But it’s not unique for everyday Ohioans.
          We need more leaders at the Statehouse who’ve been where I’ve been.
          Then we can propose
          %a{href: issues_path} solutions
          that we know from experience will work.

          %br Join our campaign today!

        = form_for @contact, url: new_volunteer_path, html: {class: 'order-md-1'} do |f|
          = error_messages_for 'contact'
          .form-row.mb-4
            .col
              = f.text_field :first_name, class: 'form-control', required: 'required', placeholder: 'First name'
            .col
              = f.text_field :last_name, class: 'form-control', required: 'required', placeholder: 'Last name'
          .form-row.mb-4
            .col
              = f.email_field :email, class: 'form-control', required: 'required', placeholder: 'Email address'
            .col-auto
              = recaptcha_v3(action: 'volunteer')
              = f.submit "Stay connected", class: "btn btn-danger lift"
%section.pt-8
  .container
    .row.justify-content-center.pt-6
      .col-12.col-md-10.col-lg-8.text-center
        = render partial: 'layouts/partials/alerts'
        %span.badge.badge-pill.badge-primary-soft.mb-3
          %span.h6.text-uppercase Platform
        %h2.font-weight-bold
          It's time to put
          %span.text-danger people over profit.
        %p.font-size-lg.text-muted.mb-8
          Your hard work should benefit you and not just corporations.
          We need better-paying jobs and a government that works for us and not just special interests.
    .row
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-3{"data-aos": "fade-up"}
        .icon-circle.bg-primary.text-white
          %i.fa.fa-user-hard-hat.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Economy
        %p.text-muted.mb-8.mb-md-0
          Our economic policies reward the thinking up top and take advantage of the labor that's also responsible
          for our success. We need a Living Wage to make sure this economy works for everyone.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-3{"data-aos": "fade-up"}
        .icon-circle.bg-danger.text-white
          %i.fa.fa-school.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Education
        %p.text-muted.mb-8.mb-lg-0
          Ohio's schools are poorly funded and have fallen behind other States.
          We need to fix our funding formula so that the quality of a child's education doesn't depend on their zip code.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-3{"data-aos": "fade-up"}
        .icon-circle.bg-primary.text-white
          %i.fa.fa-user-md.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Healthcare
        %p.text-muted.mb-8
          Affordable healthcare and prescription drugs are a right, not a privilege.
          We have to limit the profits of the pharmaceutical industry on life-saving medications.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-5{"data-aos": "fade-up"}
        .icon-circle.bg-danger.text-white
          %i.fa.fa-venus.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Women's Rights
        %p.text-muted.mb-0
          It's a fundamental right for a woman to have control of her body. That right needs to be defended and expanded.
          We also have to eliminate the pay discrimination that women face.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-5{"data-aos": "fade-up"}
        .icon-circle.bg-primary.text-white
          %i.fa.fa-balance-scale.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Criminal Justice
        %p.text-muted.mb-0
          Our policies have to focus on rehabilitation rather than punishment.
          The prison industry has pushed policies that ensure profits for private prisons.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-3{"data-aos": "fade-up"}
        .icon-circle.bg-danger.text-white
          %i.fa.fa-university.fa-2x
        %h3.font-weight-bold.text-primary.mt-1.mt-1
          Democracy
        %p.text-muted.mb-8
          Gerrymandering and expensive campaigns have moved control out of the hands of the voters and into special
          interests and lobbyists.

      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-5{"data-aos": "fade-up"}
        .icon-circle.bg-primary.text-white
          %i.fa.fa-globe-americas.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Environment
        %p.text-muted.mb-8
          In the past forty years, the free market hasn't solved climate change.
          We must do everything we can to ensure the survival of our children and resources.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-5{"data-aos": "fade-up"}
        .icon-circle.bg-danger.text-white
          %i.fa.fa-users.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          LGBTQ+
        %p.text-muted.mb-0
          Ohio must strive to be an open and inclusive state. We must ensure that no one ever faces discrimination based
          on their sexual orientation, gender identity, or gender expression.
      .col-12.col-md-6.col-lg-4.text-center.aos-init.aos-animate.mb-5{"data-aos": "fade-up"}
        .icon-circle.bg-primary.text-white
          %i.fa.fa-cloud.fa-2x
        %h3.font-weight-bold.text-primary.mt-1
          Technology
        %p.text-muted.mb-0
          Our children aren't prepared for an increasingly online world.
          We ignore businesses profiting off data collected about us as we use apps and browse the web.
%section.pt-6
  .container.pb-6.pb-md-8
    .row.align-items-center
      .col-12.col-md
        %h3.font-weight-bold.mb-1.text-danger
          Now is the time to move Ohio forward
        %p.font-size-lg.text-muted.mb-6.mb-md-0
          A living wage, affordable healthcare, prescription drugs pricing should be our top priorities.
          Want to know how we're getting it done?
      .col-12.col-md-auto
        %a.btn.btn-primary.lift{href: issues_path}
          Read my plans for Ohio
          %i.fad.fa-chevron-double-right.d-none.d-md-inline.ml-3
%section.pt-6.mb-8
  .container
    .row.align-items-center.justify-content-between.mb-8
      .col-12.col-md-6.aos-init.aos-animate{"data-aos": "fade-left"}
        %h2
          We're fighting for
          %span.text-danger
            %span{"data-strings": "[\"the right to affordable healthcare.\",\"a woman's right to choose.\",\"economic security.\",\"an end to LGBTQ+ descrimination.\",\"quality schools for our children.\",\"control of our democracy.\",\"affordable childcare.\",\"equal justice for all and so much more!\"]", "data-toggle": "typed"}
        %p.font-size-lg.text-muted.mb-5
          In 2020, we have an opportunity to take back our state and set it on the right path.
          An opportunity for better-funded schools, a Living Wage for everyone, and a healthcare system that puts
          %span.text-danger people over profit.
          %a{href: issues_path}
            Learn more about everything we want to do for Ohioians.
        %h5.font-weight-bold.mt-3.mb-3.text-primary
          Stay connected on social media
        = render partial: 'layouts/partials/media_buttons'
        -# %a.btn.btn-primary.btn-block.lift.mt-6{href: donate_url}
        -#   Help spread our message to voters
      .col-12.col-md-6.col-lg-5.order-md-1.aos-init.aos-animate{"data-aos": "fade-right"}
        .card.shadow-light-lg.lift.lift-lg
          %img.card-img-top{alt: "The campaign team during Columbus Pride 2019", src: asset_path('TheTeam.jpeg')}
          .position-relative
            .shape.shape-bottom.shape-fluid-x.svg-shim.text-white
              %svg{fill: "none", preserveaspectratio: "none", viewbox: "0 0 1440 24", xmlns: "http://www.w3.org/2000/svg"}
                %path{d: "M0 24H1440V0C722.5 52 0 0 0 0V24Z", fill: "currentColor"}
          -# .card-body
          -#   = form_for @contact, url: new_volunteer_path do |f|
          -#     %h3.text-primary Join our team today!
          -#     = error_messages_for 'contact'
          -#     = f.hidden_field :id
          -#     .form-label-group
          -#       .form-label-group
          -#         = f.text_field :first_name, class: 'form-control form-control-flush', required: 'required', placeholder: 'First name'
          -#         = f.label :first_name
          -#       .form-label-group
          -#         = f.text_field :last_name, class: 'form-control form-control-flush', required: 'required', placeholder: 'Last name'
          -#         = f.label :last_name
          -#       .form-label-group
          -#         = f.email_field :email, class: 'form-control form-control-flush', required: 'required', placeholder: 'Email address'
          -#         = f.label :email
          -#       .form-label-group
          -#         = f.text_field :zip_code, class: 'form-control form-control-flush', required: 'required', placeholder: 'Zip Code'
          -#         = f.label :zip_code
          -#       .form-label-group
          -#         = f.text_field :phone_number, class: 'form-control form-control-flush', placeholder: 'Phone number'
          -#         = f.label :phone_number
          -#     = f.submit "Sign up", class: "btn btn-block btn-danger lift"
          -#     = recaptcha_v3(action: 'volunteer')
    .row.align-items-center.mb-5
      .col-12.col-md-6.order-md-2.aos-init.aos-animate{"data-aos": "fade-right"}
        %h2
          Where is
          %span.text-danger District 16
          at exactly?
        %p.font-size-lg.text-muted.mb-5
          The district encompasses the majority of western the half of Franklin County and most of north-west Columbus.
          %a.text-primary.font-size-sm{href: "https://statisticalatlas.com/state-upper-legislative-district/Ohio/State-Senate-District-16/Overview", target: "_blank"}
            Source and additional information.
        .row
          .col-12.col-lg-6
            .d-flex
              .badge.badge-rounded-circle.badge-primary-soft.mt-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Dublin
            .d-flex
              %span.badge.badge-rounded-circle.badge-primary-soft.mt-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Grove City
          .col-12.col-lg-6
            .d-flex
              .badge.badge-rounded-circle.badge-primary-soft.mr-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Harrisburg
            .d-flex
              %span.badge.badge-rounded-circle.badge-primary-soft.mt-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Hilliard
          .col-12.col-lg-6
            .d-flex
              .badge.badge-rounded-circle.badge-primary-soft.mt-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Parts of Columbus
            .d-flex
              %span.badge.badge-rounded-circle.badge-primary-soft.mt-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Riverlea
          .col-12.col-lg-6
            .d-flex
              .badge.badge-rounded-circle.badge-primary-soft.mr-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Upper Arlington
            .d-flex
              .badge.badge-rounded-circle.badge-primary-soft.mr-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Urbancrest
          .col-12.col-lg-6
            .d-flex
              %span.badge.badge-rounded-circle.badge-primary-soft.mt-1.mr-4
                %i.fas.fa-dot-circle
              %p.text-primary
                Worthington
      .col-12.col-md-6.order-md-1
        %img.screenshot.img-fluid.mb-3{alt: "...", src: asset_path('District.png')}
= content_for :scripts do
  :javascript
    (function () {
      var toggle = document.querySelectorAll('[data-toggle="typed"]');
      function init(elem) {
        var typed = new Typed(elem, {
          strings: JSON.parse(elem.dataset.strings),
          typeSpeed: 40,
          backSpeed: 40,
          backDelay: 1250,
          loop: true
        })
      }
      if (toggle) {
        [].forEach.call(toggle, function (elem) {
          console.log('init called');
          init(elem);
        });
      }
    })();