config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  # direct :donate do |form: 'adkinsforohio', ref: 'website', amount: nil, recurring: false|
  #   url = "https://secure.actblue.com/donate/#{form}?refcode=#{ref}"
  #   url += "&amount=#{amount}" unless amount.nil?
  #   url += '&recurring=1' if recurring
  #   url
  # end

  direct :facebook do
    'https://www.facebook.com/adkinsforohio'
  end

  direct :twitter do
    'https://www.twitter.com/adkinsforohio'
  end

  direct :instagram do
    'https://www.instagram.com/adkinsforohio'
  end

  direct :gitlab do
    'https://gitlab.com/mythcoders/adkinsforohio'
  end

  direct :youtube do
    'https://www.youtube.com/channel/UCc8anT7XR-VvBHfYX9XHS8g'
  end

  direct :reddit do
    'https://www.reddit.com/u/adkinsforohio'
  end

  get 'about', to: 'home#about'
  get 'contact', to: 'home#contact'
  get 'endorsements', to: 'home#endorsements'
  get 'events', to: 'home#events'
  get 'volunteer', to: 'volunteer#index'
  post 'volunteer', to: 'volunteer#create', as: 'new_volunteer'

  scope :news do
    root to: 'news#index', as: 'news'
    get 'sb208-abortion-misinformation', to: 'news#sb208', as: 'news_sb208'
    get 'suspension', to: 'news#suspension', as: 'news_suspension'
  end

  scope :issues do
    root to: 'issues#index', as: 'issues'
    get 'healthcare', to: 'issues#healthcare'
    get 'education', to: 'issues#education'
    get 'economy', to: 'issues#economy'
    get 'democracy', to: 'issues#democracy'
    get 'environment', to: 'issues#environment'
    get 'technology', to: 'issues#technology'
    get 'guns', to: 'issues#guns'
    get 'justice', to: 'issues#justice'
    get 'lgbtq', to: 'issues#lgbtq'
    get 'womens_rights', to: 'issues#womens_rights'
    get 'rural', to: 'issues#rural'
    get 'seniors', to: 'issues#seniors'
    get 'transportation', to: 'issues#transportation'
    get 'veterans', to: 'issues#veterans'
  end

  get '/missioncontrol' => redirect('/mc')
  get '/mission_control' => redirect('/mc')
  scope module: :mission_control, path: 'mc', as: 'mc' do
    root to: 'dashboard#index', as: 'dashboard'
    get 'finances', to: 'dashboard#finances', as: 'finances_dashboard'
    get 'about', to: 'dashboard#about', as: 'about'
    resources :call_sessions
    resources :contacts
    resources :contribution_forms
    resources :contribution_types
    resources :contributions
    resources :events
    resources :expense_types
    resources :expenses
    resources :political_parties
    resources :volunteer_duties
  end
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
end

app/views/news/index.html.haml
- page_title 'News'

#fb-root
%script{async: "", crossorigin: "anonymous", defer: "defer", src: "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3"}

.row.mt-5
  .col-12
    .row.mb-6.mb-md-8
      .col-auto
        .icon-circle.bg-danger.text-white
          %i.fa.fa-newspaper.fa-2x
      .col.ml-n4
        %h2.font-weight-bold.mb-0
          News
        %p.font-size-lg.text-gray-700.mb-0
          Announcements and highlights from the campaign trail

  .col-12.col-md-8
    .list-group
      .list-group-item
        .mr-auto
          %h3.font-weight-bold.mb-0.text-primary
            = link_to "Statement from Candidate Justin Adkins", news_suspension_path
          %p.font-size-lg.text-gray-700.mb-0
            %i.fa.fa-calendar
            Thursday, Janurary 23, 2020
      .list-group-item
        .mr-auto
          %h3.font-weight-bold.mb-0.text-primary
            = link_to "Candidate Justin Adkins Condems Kunze’s Vote for Extremist Abortion Misinformation Bill", news_sb208_path
          %p.font-size-lg.text-gray-700.mb-0
            %i.fa.fa-calendar
            Friday, November 8, 2019
  .col-12.col-md-4
    .fb-page{"data-adapt-container-width": "true", "data-height": "", "data-hide-cover": "false", "data-href": facebook_url, "data-show-facepile": "true", "data-small-header": "false", "data-tabs": "timeline,events", "data-width": ""}
      %blockquote.fb-xfbml-parse-ignore{cite: facebook_url}
        %a{href: facebook_url} Justin Adkins for Ohio Senate

%section.pt-6
  .row.align-items-center
    .col-12.col-md
      %h3.font-weight-bold.mb-1.text-danger
        Stay connected on social media
      %p.font-size-lg.text-muted.mb-6.mb-md-0
        With your help, our democracy can be one person, one vote!
    .col-12.col-md-auto
      = render partial: 'layouts/partials/media_buttons'

app/views/news/sb208.html.haml
- page_title "Candidate Justin Adkins Condems Kunze’s Vote for Extremist Abortion Misinformation Bill", 'News'

.row.mt-5
  .col-12
    .row.mb-6.mb-md-8
      .col-auto
        .icon-circle.bg-danger.text-white
          %i.fa.fa-newspaper.fa-2x
      .col.ml-n4
        %h2.font-weight-bold.mb-0
          CANDIDATE JUSTIN ADKINS CONDEMNS KUNZE'S VOTE FOR EXTREMIST ABORTION MISINFORMATION BILL
        %p.font-size-lg.text-gray-700.mb-0
          Friday, November 8, 2019
.row
  .col-12.col-md-9
    %p.card-text
      COLUMBUS, OH – Candidate for the Ohio Senate District 16 Justin Adkins of Columbus, OH offered the following
      comments on a decision by his opponent, Senator Stephanie Kunze, to vote for Senate Bill 208.
    %p.card-text
      “GOP Senators once again appear to be putting special-interests above the needs of Ohioans by pushing more
      partisan abortion laws through the Senate,” said a disappointed Adkins. “Senator Stephanie Kunze voted for
      SB 208 which expands on abortion laws that are already on the books by seeking to criminalize physicians who
      provide abortions. The bill creates more bureaucratic overhead and extra work with required monthly and yearly
      reports, and draconian penalties for failing to file those reports.”
    %p.card-text
      Failure to comply with the bill’s provisions would subject the physician to a third degree felony, as well as
      all related court costs, just for spite.
    %p.card-text
      “In 2020, Senator Kunze has a performance review scheduled with the people of the 16th District. I would think
      she’d want to focus on real priorities like affordable healthcare and higher-wage jobs rather than wasting
      taxpayer dollars trying to shame women and punish doctors for doing their job.”
    %p.card-text
      Adkins is fighting to bring evidenced-based solutions and an outsider’s perspective to the Statehouse.
      As a software developer and small business owner running on a platform of people over profit, Justin wants to
      move Ohio forward by tackling the skyrocketing costs of life-saving drugs like Insulin and Epi-Pen. More
      information about Justin’s campaign platform can be found at
      = link_to 'here.', issues_path, class: 'card-link'
    %p.card-text.text-center
      = "###"
  .col-12.col-md-3
    = render partial: 'layouts/partials/media_contact'
    %a{href: '/adkins-sb208.pdf'}
      %i.fa.fa-file-pdf
      PDF Download
%section.pt-6
  .row.align-items-center
    .col-12.col-md
      %h3.font-weight-bold.mb-1.text-danger
        Stay connected on social media
      %p.font-size-lg.text-muted.mb-6.mb-md-0
        With your help, our democracy can be one person, one vote!
    .col-12.col-md-auto
      = render partial: 'layouts/partials/media_buttons'

app/views/news/suspension.html.haml
- page_title "Statement from Candidate Justin Adkins", 'News'

.row.mt-5
  .col-12
    .row.mb-6.mb-md-8
      .col-auto
        .icon-circle.bg-danger.text-white
          %i.fa.fa-newspaper.fa-2x
      .col.ml-n4
        %h2.font-weight-bold.mb-0.text-uppercase
          Statement from Candidate Justin Adkins
        %p.font-size-lg.text-gray-700.mb-0
          Thursday, Janurary 23, 2020
.row
  .col-12.col-md-9
    %p.card-text
      COLUMBUS, OH – I joined this race because our district needs a champion in the Ohio Senate. More and more of our
      neighbors are unable to afford access to quality healthcare or their life-saving prescription drugs.
      At the same time, we’re facing stagnant wages and the rising cost of everything from childcare to education.
      I know from personal experience how devastating these barriers can be.
    %p.card-text
      In 2020, we have an opportunity to take back our state and set it on the right path. We need bold new leadership
      to tackle the challenges that lie ahead. We don’t have time for politics as usual.
    %p.card-text
      Over the past few weeks, I’ve come to realize that I am not currently in a position to be the candidate with the
      best shot at flipping this district and improving life for its residents.
    %p.card-text
      That is why I’m announcing my decision to suspend my campaign for the Democratic Party’s nomination for Ohio
      Senate District 16.
    %p.card-text
      My volunteers, supporters, and the residents of SD 16 deserve a nominee with the strongest chance at beating the
      Statehouse supermajority in November.
    %p.card-text
      That is why tonight I gladly throw my support behind
      %a{href: "https://www.lettforohio.com/home"} Crystal Lett.
    %p.card-text
      Our communities need someone to fight for access to affordable healthcare and prescription drugs. Someone to make
      sure our children attend safe and properly funded schools. Crystal is the fighter we need to deliver us these wins
      for our children and communities. Crystal is the strongest candidate and best person to turn District 16 blue in
      2020.
    %p.card-text
      To those whose support has brought me this far, I am deeply honored to have earned your trust.
      I’m sorry that I wasn’t able to carry us over the finish line this time. But this is only the beginning of my
      efforts to serve and improve Central Ohio. I know we will accomplish big things together in the months and years
      to come.
    %p.card-text
      For now, I look forward to working with you to win SD 16 for Crystal Lett on March 17th and again in November.
    %p.card-text.text-center
      = "###"
  .col-12.col-md-3
    = render partial: 'layouts/partials/media_contact'
    %a{href: '/adkins-suspension.pdf'}
      %i.fa.fa-file-pdf
      PDF Download
%section.pt-6
  .row.align-items-center
    .col-12.col-md
      %h3.font-weight-bold.mb-1.text-danger
        Stay connected on social media
      %p.font-size-lg.text-muted.mb-6.mb-md-0
        With your help, our democracy can be one person, one vote!
    .col-12.col-md-auto
      = render partial: 'layouts/partials/media_buttons'